server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: us-service
          uri: lb://us-service
          predicates:
            - Path=/api/users/**

        - id: inv-service
          uri: lb://inv-service
          predicates:
            - Path=/api/inventories/**

        - id: rep-service
          uri: lb://rep-service
          predicates:
            - Path=/api/reports/**

        - id: ord-service
          uri: lb://ord-service
          predicates:
            - Path=/api/orders/**

        - id: not-service
          uri: lb://not-service
          predicates:
            - Path=/api/notifications/**
  sleuth:
    enabled: false
    sampler: 0.0
  zipkin:
    enables: false

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URI}
