server:
  port: 0

spring:
  application:
    name: inv-service
  data:
    mongodb:
      uri: ${MONGOURI_INVENTORIES}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  security:
    api:
      key: ${API_KEY}
    admin:
      mail: ${ADMIN_MAIL}
      password: ${ADMIN_PASSWORD}
  sleuth:
    enabled: false
    sampler: 0.0
  zipkin:
    enables: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: ${RABBIT_EXCHANGE_NAME}
  inventory:
    routing:
      key:
        string:
          name: ${RABBIT_INVENTORY_STRING_ROUTING_KEY}
        json:
          name: ${RABBIT_INVENTORY_JSON_ROUTING_KEY}
