server:
  port: 0

spring:
  security:
    api:
      key: ${API_KEY}
  application:
    name: not-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  data:
    mongodb:
      uri: ${MONGOURI_USERS}
  sleuth:
    enabled: false
    sampler: 0.0
  zipkin:
    enables: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
      service-url:
        defaultZone: ${DISCOVERY_SERVER_URI}

rabbitmq:
  exchange:
    name: ${RABBIT_EXCHANGE_NAME}
  inventory:
    queue:
      string:
        name: ${RABBIT_INVENTORY_QUEUE_STRING_NAME}
      json:
        name: ${RABBIT_INVENTORY_QUEUE_JSON_NAME}
    routing:
      key:
        string:
          name: ${RABBIT_INVENTORY_STRING_ROUTING_KEY}
        json:
          name: ${RABBIT_INVENTORY_JSON_ROUTING_KEY}
