spring:
  profiles:
    active: @profileActive@
  application:
    name: us-service
  config:
    import: optional:configserver:${CONFIGSERVER_URI}

#logging:
#  level:
#    root: debug
#    org.springframework.web: debug
#    com.cesar.usservice: debug
